import { SplashScreen, Stack } from "expo-router";
import dayjs from 'dayjs';
import 'dayjs/locale/zh-cn'; // 引入中文本地化配置
import weekday from 'dayjs/plugin/weekday';
import localeData from 'dayjs/plugin/localeData';
import updateLocale from 'dayjs/plugin/updateLocale';
import { useEffect, useState } from "react";
import { AsyncStorage } from "expo-sqlite/kv-store";
import { ThemeProvider } from "@/context/ThemeContext";
import { AIConfigProvider } from "@/context/AIConfigContext";
import { autoGenerateYesterdayDiary } from "@/utils/autoGenerateDiaryUtils";
import { SortConfigProvider } from "@/context/SortConfigContext";

dayjs.extend(weekday);
dayjs.extend(localeData);
dayjs.extend(updateLocale);
dayjs.locale('zh-cn');
// 设置周起始为周一
dayjs.updateLocale('zh-cn', {
  weekStart: 1,
  weekEnd: 0
});

export default function RootLayout() {
  const [config, setConfig] = useState(null);
  
  // 从本地加载主题
  useEffect(() => {
    const init = async () => {
      const mode = await AsyncStorage.getItem('theme_mode');
      const primary = await AsyncStorage.getItem('theme_primary');
      const scene = await AsyncStorage.getItem('theme_scene');
      
      setConfig({
        mode,
        primary,
        scene
      });
      await SplashScreen.hideAsync();
    };
    
    SplashScreen.preventAutoHideAsync().then();
    init().then();
  }, []);
  
  // 自动生成日记
  useEffect(() => {
    autoGenerateYesterdayDiary().catch(e => {
      console.error('自动生成日记任务失败：', e);
    });
  }, []);
  
  if(!config) return null;
  
  return (
    <ThemeProvider initialConfig={config}>
      <AIConfigProvider>
        <SortConfigProvider>
          <Stack screenOptions={{ headerShown: false }} />
        </SortConfigProvider>
      </AIConfigProvider>
    </ThemeProvider>
  );
}
