import Icon from "@/components/common/Icon";
import AIStreamText from "@/components/common/AIStreamText";
import BaseModal from "@/components/common/BaseModal";
import ThemeSafeAreaView from "@/components/theme/ThemeSafeAreaView";
import ThemeButton from "@/components/theme/ThemeButton";
import { useTheme } from "@/context/ThemeContext";
import { noteApi, folderApi } from "@/api";
import { formatDatetime } from "@/utils/formatTimeUtils";
import {
  createAiDiaryServiceFromStorage,
  DEFAULT_DIARY_AI_USER_PROMPT,
  DIARY_FOLDER_NAME,
  getEventsPlainTextForDiaryDate,
  isDiaryDateTitle
} from "@/utils/autoGenerateDiaryUtils";
import { useNavigation, useRoute } from '@react-navigation/native';
import React, { useCallback, useEffect, useRef, useState } from "react";
import {
  ActivityIndicator,
  Alert,
  Text,
  TextInput,
  TouchableOpacity,
  View,
  StyleSheet
} from "react-native";
import MarkdownEditor from "@/components/common/MarkdownEditor";

export default function DiaryEdit() {
  const { theme } = useTheme();
  
  const route = useRoute();
  const navigation = useNavigation();
  const nodeId = route.params?.nodeId;
  const folderId = route.params?.folderId;
  
  const [diary, setDiary] = useState(null);
  const [content, setContent] = useState('');
  const [title, setTitle] = useState('');
  
  const [isInitializing, setIsInitializing] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [isInDiaryFolder, setIsInDiaryFolder] = useState(false);
  
  const [aiModalVisible, setAiModalVisible] = useState(false);
  const [isAiRegenerating, setIsAiRegenerating] = useState(false);
  const [isAiPaused, setIsAiPaused] = useState(false);
  const [aiStream, setAiStream] = useState({ thought: '', output: '' });
  const [aiStreamFinalized, setAiStreamFinalized] = useState(false);
  const aiServiceRef = useRef(null);
  const aiRequestIdRef = useRef(0);
  
  // 用于实现 撤销/前进 操作
  const [history, setHistory] = useState([]);
  const [historyIndex, setHistoryIndex] = useState(-1);
  
  const [originalTitle, setOriginalTitle] = useState('');
  const [originalContent, setOriginalContent] = useState('');
  
  // 编辑区/撤销保存等操作在 AI 生成中可锁定；但 AI 按钮需要允许再次打开弹窗
  const editorLocked = isSaving || isAiRegenerating;
  const aiButtonDisabled = isSaving;
  const showAiRegenerate = Boolean(nodeId && isInDiaryFolder);
  
  // 加载日记内容或初始化新日记
  useEffect(() => {
    const initializePage = async () => {
      if(nodeId) {
        setIsInitializing(true);
        try {
          const data = await noteApi.getById(nodeId);
          
          if(data) {
            setDiary({
              ...data
            });
            setContent(data.content);
            setTitle(data.title || '');
            
            setHistory([data.content]);
            setHistoryIndex(0);
            
            setOriginalTitle(data.title || '');
            setOriginalContent(data.content || '');
            
            const fid = data.folderId != null
              ? Number(data.folderId)
              : (folderId != null ? Number(folderId) : null);
            if (fid != null && !Number.isNaN(fid)) {
              try {
                const folder = await folderApi.getById(fid);
                setIsInDiaryFolder(folder?.name === DIARY_FOLDER_NAME);
              } catch {
                setIsInDiaryFolder(false);
              }
            } else {
              setIsInDiaryFolder(false);
            }
          } else {
            Alert.alert('错误', '未找到指定的日记');
            navigation.goBack();
          }
        } finally {
          setIsInitializing(false);
        }
      } else {
        setIsInDiaryFolder(false);
        const today = new Date().toISOString();
        setDiary({
          title: '',
          content: '',
          createdAt: today,
          updatedAt: today
        });
        setTitle('');
        
        setHistory(['']);
        setHistoryIndex(0);
        
        setOriginalTitle('');
        setOriginalContent('');
      }
    };
    
    initializePage().catch(err => {
      console.error("Failed to initialize page:", err);
      setIsInitializing(false);
      Alert.alert('错误', '页面加载失败');
    });
  }, [nodeId, navigation, folderId]);
  
  useEffect(() => {
    if(content !== history[historyIndex]) {
      const newHistory = history.slice(0, historyIndex + 1);
      newHistory.push(content);
      setHistory(newHistory);
      setHistoryIndex(newHistory.length - 1);
    }
  }, [content, history, historyIndex]);
  
  // 仅关闭弹窗：不取消、不清空，AI 在后台继续跑
  const closeAiModal = useCallback(() => {
    setAiModalVisible(false);
  }, []);

  // 真正取消本次生成：中断 SSE 并清空本次结果
  const cancelAiRegenerate = useCallback(() => {
    aiServiceRef.current?.pauseRequest?.();
    aiServiceRef.current = null;
    aiRequestIdRef.current += 1;
    setIsAiRegenerating(false);
    setIsAiPaused(false);
    setAiStream({ thought: '', output: '' });
    setAiStreamFinalized(false);
    setAiModalVisible(false);
  }, []);

  // 中止(暂停)：中断 SSE，但保留当前已生成的流式内容；可继续同一次请求
  const stopAiRegenerate = useCallback(() => {
    aiServiceRef.current?.pauseRequest?.();
    setIsAiRegenerating(false);
    setIsAiPaused(true);
    setAiStreamFinalized(false);
  }, []);

  const continueAiRegenerate = useCallback(async () => {
    const service = aiServiceRef.current;
    if (!service?.resumeRequest) {
      Alert.alert('提示', '当前服务不支持继续生成，请点击重新生成');
      return;
    }
    const requestId = aiRequestIdRef.current + 1;
    aiRequestIdRef.current = requestId;
    setIsAiRegenerating(true);
    setIsAiPaused(false);
    setAiModalVisible(true);
    try {
      const { thought, output } = await service.resumeRequest({
        onThought: (t) => {
          if (aiRequestIdRef.current !== requestId) return;
          setAiStream(prev => ({ ...prev, thought: t }));
        },
        onOutput: (o) => {
          if (aiRequestIdRef.current !== requestId) return;
          setAiStream(prev => ({ ...prev, output: o }));
        }
      });
      const body = (output || '').trim();
      if (!body) {
        Alert.alert('提示', 'AI 返回内容为空');
        return;
      }
      if (aiRequestIdRef.current !== requestId) return;
      setAiStream({
        thought: (thought || '').trim(),
        output: body
      });
      setAiStreamFinalized(true);
    } catch (e) {
      console.error('继续生成失败:', e);
      Alert.alert('错误', e.message || '继续生成失败，请重试');
    } finally {
      if (aiRequestIdRef.current === requestId) {
        setIsAiRegenerating(false);
      }
    }
  }, []);

  const handleApplyAiResult = () => {
    const body = (aiStream.output || '').trim();
    if (!body) {
      Alert.alert('提示', '没有可应用的内容');
      return;
    }
    setContent(body);
    // 应用后仅关闭弹窗；保留生成结果，方便再次查看
    setAiModalVisible(false);
  };
  
  const startAiRegenerate = async ({ forceNew = false } = {}) => {
    // 若已有同一次请求在跑 / 已生成完毕，则直接打开弹窗复用结果
    if (!forceNew && (isAiRegenerating || aiStreamFinalized || aiStream.thought || aiStream.output)) {
      setAiModalVisible(true);
      return;
    }

    if (!isDiaryDateTitle(title)) {
      Alert.alert(
        '提示',
        'AI 重新生成需要按日期汇总事件：请将标题设为当日日期，格式 YYYY-MM-DD。'
      );
      return;
    }
    
    const dateStr = title.trim();
    const { service, error } = await createAiDiaryServiceFromStorage();
    if (error) {
      Alert.alert('提示', error);
      return;
    }
    
    const { events, text: dailyEventsText } = await getEventsPlainTextForDiaryDate(dateStr);
    if (!events?.length) {
      Alert.alert('提示', `日期 ${dateStr} 暂无事件数据，无法生成日记。`);
      return;
    }
    
    const dailyPrompt = service.generateDiaryPrompt(
      dateStr,
      dateStr,
      dailyEventsText || '',
      DEFAULT_DIARY_AI_USER_PROMPT
    );
    
    const requestId = aiRequestIdRef.current + 1;
    aiRequestIdRef.current = requestId;
    aiServiceRef.current = service;
    setAiStream({ thought: '', output: '' });
    setAiStreamFinalized(false);
    setIsAiPaused(false);
    setAiModalVisible(true);
    setIsAiRegenerating(true);
    
    try {
      const { thought, output } = await service.generateContent(dailyPrompt, {
        onThought: (t) => {
          if (aiRequestIdRef.current !== requestId) return;
          setAiStream(prev => ({ ...prev, thought: t }));
        },
        onOutput: (o) => {
          if (aiRequestIdRef.current !== requestId) return;
          setAiStream(prev => ({ ...prev, output: o }));
        }
      });
      
      const body = (output || '').trim();
      if (!body) {
        Alert.alert('提示', 'AI 返回内容为空');
        cancelAiRegenerate();
        return;
      }
      
      if (aiRequestIdRef.current !== requestId) return;
      setAiStream({
        thought: (thought || '').trim(),
        output: body
      });
      setAiStreamFinalized(true);
    } catch (e) {
      console.error('AI 重新生成失败:', e);
      Alert.alert('错误', e.message || '生成失败，请检查网络与 API 配置');
      cancelAiRegenerate();
    } finally {
      // 若用户取消了本次请求（requestId 已变化），不要覆盖其状态
      if (aiRequestIdRef.current === requestId) {
        setIsAiRegenerating(false);
        aiServiceRef.current = null;
      }
    }
  };

  const handleAiRegenerate = () => startAiRegenerate({ forceNew: false });

  const handleAiForceRegenerate = async () => {
    // 若正在生成，先中止当前请求，再重新发起
    if (isAiRegenerating) {
      stopAiRegenerate();
    }
    await startAiRegenerate({ forceNew: true });
  };

  const handleGoBack = () => {
    if (navigation.canGoBack()) {
      navigation.goBack();
      return;
    }
    Alert.alert('提示', '当前页面无法返回上一页');
  };
  
  // 撤销功能
  const handleUndo = () => {
    if(historyIndex > 0) {
      const newIndex = historyIndex - 1;
      setContent(history[newIndex]);
      setHistoryIndex(newIndex);
    }
  };
  
  // 重做功能
  const handleRedo = () => {
    if(historyIndex < history.length - 1) {
      const newIndex = historyIndex + 1;
      setContent(history[newIndex]);
      setHistoryIndex(newIndex);
    }
  };
  
  const isContentChanged = () => {
    const trimmedContent = content.trim();
    return title.trim() !== originalTitle.trim() || trimmedContent !== originalContent.trim();
  };
  // 保存日记（新建或更新）
  const handleSave = async () => {
    if(!title.trim()) {
      Alert.alert('提示', '标题不能为空');
      return;
    }
    
    const trimmedContent = content.trim();
    if(!trimmedContent) {
      Alert.alert('提示', '内容不能为空');
      return;
    }
    
    setIsSaving(true);
    let success = false;
    const updatedAt = new Date().toISOString(); // 获取当前时间作为更新时间
    
    try {
      if(nodeId) {
        // 更新日记时，同时更新标题、内容和更新时间
        const updateResponse = await noteApi.update(nodeId, {
          title,
          content: trimmedContent
        });
        success = updateResponse.success;
        // 更新本地状态以反映最新变化
        setDiary(prev => ({
          ...prev,
          title,
          content: trimmedContent,
          updatedAt
        }));
      } else {
        const createdAt = new Date().toISOString();
        const newDiaryResponse = await noteApi.create({
          title,
          content: trimmedContent,
          folderId
        });
        const newDiaryId = newDiaryResponse.id;
        success = !!newDiaryId;
        if(success) {
          setDiary(prev => ({
            ...prev,
            id: newDiaryId,
            title,
            content: trimmedContent,
            createdAt,
            updatedAt
          }));
        }
      }
    } catch(error) {
      console.error("Failed to save diary:", error);
    } finally {
      setIsSaving(false);
    }
    
    if(success) {
      Alert.alert('成功', nodeId ? '日记已更新' : '日记已创建');
      navigation.goBack();
    } else {
      Alert.alert('失败', '保存日记时出错，请稍后重试');
    }
  };
  
  if(isInitializing && !diary) {
    return (
      <View style={styles.loadingContainer}>
        <ActivityIndicator size="large" color="#007AFF" />
      </View>
    );
  }
  
  // 计算字数
  const wordCount = content.length || 0;
  
  return (
    <ThemeSafeAreaView style={styles.container}>
      {/* 顶部导航 */}
      <View style={styles.header}>
        <TouchableOpacity
          style={styles.backButton}
          onPress={handleGoBack}
          hitSlop={{ top: 12, bottom: 12, left: 12, right: 12 }}
          accessibilityLabel="返回"
        >
          <Icon lib="Ionicons" name="arrow-back" size={24} />
        </TouchableOpacity>
        
        <View style={styles.controls}>
          {showAiRegenerate && (
            <TouchableOpacity
              onPress={handleAiRegenerate}
              disabled={aiButtonDisabled}
              style={styles.iconButton}
              accessibilityLabel="AI 重新生成"
            >
              <Icon
                lib="Ionicons"
                name="sparkles"
                size={24}
                color={
                  aiButtonDisabled
                    ? theme.colors.interactiveLight
                    : theme.colors.interactive
                }
              />
            </TouchableOpacity>
          )}
          
          {/* 撤销 */}
          <TouchableOpacity
            onPress={handleUndo}
            disabled={historyIndex <= 0 || editorLocked}
            style={styles.iconButton}
          >
            <Icon
              lib={"MaterialCommunityIcons"}
              name="undo-variant"
              size={24}
              color={
                historyIndex <= 0 || editorLocked
                  ? theme.colors.interactiveLight
                  : theme.colors.interactive
            }
            />
          </TouchableOpacity>
          
          {/* 重做 */}
          <TouchableOpacity
            onPress={handleRedo}
            disabled={historyIndex >= history.length - 1 || editorLocked}
            style={styles.iconButton}
          >
            <Icon
              lib={"MaterialCommunityIcons"}
              name="redo-variant"
              size={24}
              color={
                historyIndex >= history.length - 1 || editorLocked
                  ? theme.colors.interactiveLight
                  : theme.colors.interactive
              }
            />
          </TouchableOpacity>
          
          <TouchableOpacity
            onPress={handleSave}
            style={styles.iconButton}
          >
            <Icon
              lib={"Ionicons"}
              name="checkmark"
              size={24}
              color={
                isContentChanged() && !editorLocked
                  ? theme.colors.interactive
                  : theme.colors.interactiveLight
              }
            />
          </TouchableOpacity>
        </View>
      </View>
      
      {/* 保存中 */}
      {isSaving && (
        <View style={styles.loadingOverlay}>
          <ActivityIndicator size="large" color="#007AFF" />
        </View>
      )}
      
      <BaseModal
        visible={aiModalVisible}
        onClose={closeAiModal}
        title="AI 重新生成"
        showFooter={false}
      >
        <View style={styles.aiModalBody}>
          <View style={styles.aiStreamWrap}>
            <AIStreamText
              content={{ thought: aiStream.thought, output: aiStream.output }}
              isContentFinalized={aiStreamFinalized}
            />
          </View>

          {/* 生成中：中止/继续/重新生成在内容区；生成结束：底部同一行展示 取消 | 重新生成 | 应用到正文 */}
          {(!isAiRegenerating && aiStreamFinalized) ? (
            <View style={styles.aiFooterRow}>
              <ThemeButton
                style={styles.aiFooterCancelBtn}
                onPress={closeAiModal}
                title="取消"
                active={false}
                textStyle={styles.aiFooterCancelText}
              />
              <View style={styles.aiFooterRight}>
                <ThemeButton
                  style={styles.aiFooterRegenerateBtn}
                  onPress={handleAiForceRegenerate}
                  title="重新生成"
                  active={false}
                  textStyle={styles.aiFooterRegenerateText}
                />
                <ThemeButton
                  style={styles.aiFooterApplyBtn}
                  onPress={handleApplyAiResult}
                  title="应用到正文"
                />
              </View>
            </View>
          ) : (
            <View style={styles.aiActionRow}>
              {isAiRegenerating ? (
                <TouchableOpacity
                  onPress={stopAiRegenerate}
                  style={styles.aiActionBtn}
                  accessibilityLabel="中止生成"
                >
                  <Text style={[styles.aiActionBtnText, { color: theme.colors.interactive }]}>
                    中止
                  </Text>
                </TouchableOpacity>
              ) : isAiPaused ? (
                <TouchableOpacity
                  onPress={continueAiRegenerate}
                  style={styles.aiActionBtn}
                  accessibilityLabel="继续生成"
                >
                  <Text style={[styles.aiActionBtnText, { color: theme.colors.interactive }]}>
                    继续
                  </Text>
                </TouchableOpacity>
              ) : null}
              <TouchableOpacity
                onPress={handleAiForceRegenerate}
                style={styles.aiActionBtn}
                accessibilityLabel="重新生成"
                disabled={aiButtonDisabled}
              >
                <Text
                  style={[
                    styles.aiActionBtnText,
                    { color: aiButtonDisabled ? theme.colors.interactiveLight : theme.colors.interactive }
                  ]}
                >
                  重新生成
                </Text>
              </TouchableOpacity>
            </View>
          )}
        </View>
      </BaseModal>
      
      <View style={styles.contentContainer}>
        <View>
          <TextInput
            style={[styles.titleInput, {color: theme.colors.interactive}]}
            value={title}
            onChangeText={setTitle}
            placeholder="请输入标题"
            placeholderTextColor="#999"
            editable={!editorLocked}
            autoFocus={!nodeId}
            maxLength={100}
          />
          
          <View style={styles.infoBar}>
            {/* 左侧信息：更新时间 | 字数 */}
            <View style={styles.infoLeft}>
              <Text style={styles.infoText}>
                更新: {formatDatetime(diary?.updatedAt)} | {wordCount}字
              </Text>
            </View>
            
            {/* 右侧信息：创建时间 */}
            <View style={styles.infoRight}>
              <Text style={[{ textAlign: 'right' }, styles.infoText]}>
                创建: {formatDatetime(diary?.createdAt)}
              </Text>
            </View>
          </View>
        </View>
        
        <MarkdownEditor
          value={content}
          onChangeText={setContent}
          placeholder="请输入日记内容..."
          editable={!editorLocked}
        />
      </View>
    </ThemeSafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255,255,255,0.8)',
    justifyContent: 'center',
    zIndex: 10,
  },
  
  header: {
    height: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  controls: {
    flexDirection: 'row',
    gap: 16,
    alignItems: 'center',
  },
  iconButton: {
    padding: 8,
    borderRadius: 8,
  },
  backButton: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 8,
    minWidth: 44,
    minHeight: 44,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2,
  },
  
  contentContainer: {
    flex: 1,
  },
  titleInput: {
    minHeight: 30,
    lineHeight: 30,
    paddingVertical: 8,
    paddingHorizontal: 0,
    fontSize: 18,
    fontWeight: 'bold'
  },
  infoBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 5,
  },
  infoLeft: {
    width: '50%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  infoRight: {
    width: '50%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  infoText: {
    flex: 1,
    fontSize: 12,
    color: '#666',
    numberOfLines: 1,
  },
  infoSeparator: {
    fontSize: 12,
    color: '#666',
  },
  aiModalBody: {
    flex: 1,
  },
  aiStreamWrap: {
    flex: 1,
    minHeight: 220,
  },
  aiActionRow: {
    marginTop: 12,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 14,
    alignItems: 'center',
    paddingVertical: 6,
  },
  aiActionBtn: {
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  aiActionBtnText: {
    fontSize: 16,
    fontWeight: '600',
  },
  aiFooterRow: {
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  aiFooterRight: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: 10,
  },
  aiFooterCancelBtn: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ddd',
  },
  aiFooterCancelText: {
    fontWeight: '500',
  },
  aiFooterRegenerateBtn: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ddd',
  },
  aiFooterRegenerateText: {
    fontWeight: '600',
  },
  aiFooterApplyBtn: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 8,
  },
});
