import dayjs from 'dayjs';
import { noteApi } from '@/api';
import { eventApi } from '@/api/EventApi';
import {
  createAiDiaryServiceFromStorage,
  DEFAULT_DIARY_AI_USER_PROMPT,
  DIARY_FOLDER_NAME,
  getOrCreateFolder,
} from '@/utils/autoGenerateDiaryUtils';
import { formatExtrasSummaryForCategory } from '@/utils/categoryExtrasRegistry';
import { isJournalSnippet } from '@/utils/journalExtrasUtils';
import { getPlainTextContent } from '@/utils/previewFormatter';

/**
 * 将当日事件整理为日记（优先 AI，失败则纯文本合并）
 * @param {string} dateStr YYYY-MM-DD
 */
export async function compileDailyDiary(dateStr) {
  const events = await eventApi.getByDateRangeAndCategory({
    startDate: dateStr,
    endDate: dateStr,
    sortOrder: 'asc',
  });

  if (!events.length) {
    return { ok: false, message: '当天没有可整理的事件' };
  }

  const diaryFolder = await getOrCreateFolder(DIARY_FOLDER_NAME);
  const existsResponse = await noteApi.checkDiaryExists(dateStr);
  if (existsResponse.exists) {
    return { ok: false, message: '该日期的日记已存在，请到日记页查看或编辑' };
  }

  const { service, error } = await createAiDiaryServiceFromStorage();

  let content = '';
  if (service) {
    const eventsText = getPlainTextContent('txt', events);
    const prompt = service.generateDiaryPrompt(
      dateStr,
      dateStr,
      eventsText,
      DEFAULT_DIARY_AI_USER_PROMPT
    );
    const { output } = await service.generateContent(prompt);
    content = output?.trim() || '';
  }

  if (!content) {
    content = buildPlainDiaryFromEvents(dateStr, events);
    if (error && events.length > 0) {
      content = `（未配置 AI，以下为自动合并稿）\n\n${content}`;
    }
  }

  if (!content.trim()) {
    return { ok: false, message: '整理结果为空' };
  }

  await noteApi.create({
    folderId: diaryFolder.id,
    title: dateStr,
    content: content.trim(),
  });

  return { ok: true, message: '已整理并保存到「日记」文件夹' };
}

function buildPlainDiaryFromEvents(dateStr, events) {
  const lines = [`# ${dateStr} 日记`, ''];
  const journalSnippets = events.filter(
    (e) => e.category === 'daily' && isJournalSnippet(e.extras)
  );
  const otherEvents = events.filter((e) => !journalSnippets.includes(e));

  if (journalSnippets.length) {
    lines.push('## 随手记');
    journalSnippets.forEach((e) => {
      const time = dayjs(e.startDatetime).format('HH:mm');
      const summary = formatExtrasSummaryForCategory(e.category, e.extras);
      const head = summary ? `[${time}] ${summary}` : `[${time}]`;
      lines.push(`${head} ${e.description || e.title || ''}`.trim());
    });
    lines.push('');
  }

  if (otherEvents.length) {
    lines.push('## 时间线');
    otherEvents.forEach((e) => {
      const time = dayjs(e.startDatetime).format('HH:mm');
      const extra = formatExtrasSummaryForCategory(e.category, e.extras);
      const title = e.title || extra || e.category;
      const desc = e.description ? `：${e.description}` : '';
      lines.push(`- [${time}] ${title}${desc}`);
    });
  }

  return lines.join('\n');
}
